### ISSUE TITLE
Unsupported release of RHEL

### ISSUE THREAD

**Issue by jaseeey** [mccormicka/Mockgoose#159]
When trying to install Mockgoose 5.0.2 via NPM, I receive the following error:

```bash
> mongodb-prebuilt@4.2.11 postinstall /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt
> node install.js


/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/index.js:106
					throw new Error("unsupported release of RHEL");
					      ^
Error: unsupported release of RHEL
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/index.js:106:12
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:100:16
    at done (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:132:19)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:32:16
    at async.each.cachedDistro (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:95:18)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:122:13
    at _each (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:121:9)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:80:13
    at fs.js:272:14
npm ERR! weird error 8
npm ERR! not ok code 0
```

Is Mockgoose still designed to run as a mock in-memory Mongo database, or does it now require an actual installation of MongoDB on a "supported" OS?

**Comment by winfinit** [comment]
Mockgoose is using in memory storage engine now, however it does utilize mongod, so tests are executed around exact environment. I just updated dependencies to throw better error messages, if you would be willing to try 5.0.3, and report error message from that release, then we can see what we can do about it.

**Comment by jaseeey** [comment]
Thanks for the speedy response!

I can see you've added `os.release` to the error message, but unfortunately mine is showing as `undefined`. I am running on Fedora Core 22, though it is quite a common distribution.

```bash
> mongodb-prebuilt@4.2.12 postinstall /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt
> node install.js


/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/index.js:106
					throw new Error("unsupported release of RHEL " + os.release);
					      ^
Error: unsupported release of RHEL undefined
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/index.js:106:12
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:100:16
    at done (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:132:19)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:32:16
    at async.each.cachedDistro (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:95:18)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:122:13
    at _each (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/node_modules/async/lib/async.js:121:9)
    at /home/jasey/Projects/ewp-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/node_modules/mongodb-download/node_modules/getos/index.js:80:13
    at fs.js:272:14
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by jaseeey** [comment]
I've checked it out a bit further and it appears that Fedora does not specify the `release` in the `os` object, it's simply not there. I've temporarily bypassed this by using RHEL7 as the default if there is no release, but there's probably a better way for a permanent solution?

It works fine by using the RHEL7 package for me.

Please let me know if you want any further information from me, happy to help out.

**Comment by winfinit** [comment]
@jaseeey thank you so much for your help, i've setup myself also with fedora, and it turned out that issue is actually with dependency "getos", so i've submitted a pull request with a very simple fix (https://github.com/wblankenship/getos/issues/24), where fedora is reported correctly now, and will attempt now to fix mongoldb-download with assumption that getos fix is going to get merged and published.

**Comment by jaseeey** [comment]
Great! Thank you for the quick fix, I'll keep an eye out and hopefully it gets pulled upstream soon.

**Comment by winfinit** [comment]
@jaseeey gets release was just published, so i've updated Mockgoose, and its dependencies, now 5.0.4 should solve reported problem. please let me know what other issues you may run into. thank you.

**Comment by winfinit** [comment]
closing this issue

**Comment by winfinit** [comment]
closing this issue
