### ISSUE TITLE
Wrong behavior with nested objects

### ISSUE THREAD

**Issue by ZeRego** [mccormicka/Mockgoose#161]
Schema:
```
var mySchema = Schema({
    userId: {
        type: Number
    },
    potato: {
        potatoId: {
            type: String
        },
        potatoColor: {
            type: String
        }
    }
}, {versionKey: false});
```
Code:
```
var myPotatoId = "something";
myModel.findOne({userId: userId}, function (err, doc) {
            if (err) {
                // send error
            }
            if (!doc) {
                // send error
            }
            if (!doc.potato) {
                doc.set('potato', {});
            }
            doc.set('potato.potatoId', myPotatoId);
            doc.save();
        });
```

When i run my tests i get this error:
```
TypeError: Cannot set property 'potatoId' of undefined
    at Object.setNestedValue (path\to\node_modules\mockgoose\lib\utils.js:195:44
```

This happens because he doesn't go in the if to create the empty object. 
He recognise the doc.potato isn't undefined or null when it should.

**Comment by winfinit** [comment]
@ZeRego what version of mockgoose are you using?

**Comment by ZeRego** [comment]
mockgoose "version": "2.0.1",
mongoose "version": "4.1.9",

**Comment by winfinit** [comment]
@ZeRego i've switched entire mockgoose concept now, and with latest versions will not have described issue above. I would recommend upgrading Mockgoose to mockgoose@5.0.11, and please report any issues that you may experience with it.

**Comment by ZeRego** [comment]
mockgoose "version": "5.0.11",
mongoose "version": "4.1.9",

Getting this error:

Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (...\node_modules\mongoose\lib\connection.js:216:15)
    at Mongoose.connect (...\node_modules\mongoose\lib\index.js:227:15)
    at EventEmitter.<anonymous> (...\node_modules\mockgoose\Mockgoose.js:30:22)
    at EventEmitter.<anonymous> (...\node_modules\mockgoose\Mockgoose.js:69:25)
    at Socket.<anonymous> (...\node_modules\mockgoose\node_modules\mongodb-prebuilt\index.js:71:14)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
