### ISSUE TITLE
MongoError: server sockets closed

### ISSUE THREAD

**Issue by jaseeey** [mccormicka/Mockgoose#165]
I have run into a problem where the Mongo prebuilt server appears to close when calling `res.status(200).json({})` in one of my promised functions. This is only an issue when using Mockgoose, as I can run the application without any problems at all.

```
Possibly unhandled MongoError: server localhost:27100 sockets closed
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/topologies/server.js:331:47)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/pool.js:101:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/connection.js:142:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:476:12)
Possibly unhandled MongoError: server localhost:27100 sockets closed
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/topologies/server.js:331:47)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/pool.js:101:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/connection.js:142:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:476:12)
Possibly unhandled MongoError: server localhost:27100 sockets closed
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/topologies/server.js:331:47)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/pool.js:101:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/jbi/ewp-api/node_modules/mongodb-core/lib/connection/connection.js:142:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:476:12
```

To put this in context with my code, please see below:
```
exports.find = promise.method(function (gallerySlug) {
    return Gallery.findOne({
        slug: gallerySlug
    }).execAsync()
        .then(function(gallery) {
            return gallery;
        });
});

exports.read = function (req, res) {
    var params = req.params;

    exports.find(params.gallery)
        .then(function (gallery) {
            res.status(200).json({
                data: gallery
            });
        })
        .catch(function (err) {
            res.status(err.status || 500).json({
                error: err
            });
        });
};
```

The error seems to only occur when it calls the `res.status(200).json({ data: gallery })` function, if I remove/comment this section then the error disappears and it will return data from the database. For the test, I am using `supertest` which simply makes a request to the route.

I understand the coding isn't really your issue, but is there anything to your knowledge from the Mongo prebuilt side which could be causing the server to close when I'm calling the response for ExpressJS? It just seems very odd that the error is thrown only when using Mockgoose but not when running with a live Mongo server.

**Comment by winfinit** [comment]
@jaseeey is it possible for you to put a test for me that is failing with described dependencies? I think i am following on what is happening, but not a 100%
