### ISSUE TITLE
I can't install Mockgoose

### ISSUE THREAD

**Issue by mahelder** [mccormicka/Mockgoose#193]
The problem is with my Linux distribuition, that is Mint. Any idea?

**Comment by winfinit** [comment]
during installation of mockgoose, can you please run this:

```
DEBUG=* npm install mockgoose
```

and send me your output

**Comment by mahelder** [comment]
```
npm WARN install Couldn't install optional dependency: Unsupported

> mongodb-prebuilt@4.5.5 postinstall /home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/mongodb-prebuilt
> node install.js

  mongodb-prebuilt installing version: 3.2.0 +0ms
  mongodb-download selected platform linux +4ms
  mongodb-download selected architecture x86_64 +2ms
  mongodb-download selected version: 3.2.0 +1ms
  mongodb-download os dump +5ms { os: 'linux', dist: 'Linux Mint' }
/home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/mongodb-download/index.js:141
                                throw new Error("unsupported linux distribution " + JSON.stringify(os));
                                ^

Error: unsupported linux distribution {"os":"linux","dist":"Linux Mint"}
    at /home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/mongodb-download/index.js:141:11
    at /home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/getos/index.js:100:16
    at /home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/getos/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/getos/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/getos/node_modules/async/lib/async.js:209:22)
    at /home/mahelder/Documentos/Repositories/ml-carreteiro/node_modules/getos/index.js:80:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
npm WARN EPEERINVALID mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mockgoose" "--save-dev"
npm ERR! node v4.2.1
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE

npm ERR! mongodb-prebuilt@4.5.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mongodb-prebuilt@4.5.5 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mongodb-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mahelder/Documentos/Repositories/ml-carreteiro/npm-debug.log

```

**Comment by jasiedu** [comment]
I cannot install either: It chokes here:

npm ERR! fetch failed https://github.com/winfinit/node-portfinder.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406

**Comment by winfinit** [comment]
this should be resolved with recent release.

**Comment by winfinit** [comment]
please reopen this ticket if you are still experiencing this problem with new release

**Comment by mahelder** [comment]
Sorry for slow answer...Thank you for attention @winfinit ... reallly the problem was solved with recent release...Thank you
