### ISSUE TITLE
mockgoose.reset() removes previously added data, mongoose.unmock() does nothing

### ISSUE THREAD

**Issue by SkateFreak** [mccormicka/Mockgoose#197]
```
import mockgoose from 'mockgoose'
import mongoose from 'mongoose'
import request from 'supertest'

mockgoose(mongoose);

import app from '../server/server'
const req = request(app);
```

now i add this after all tests:

```
after(function (done) {
    mockgoose.reset(function() {
        done();
    });
});
```

and it removes  the whole database, even if it was populated before hand.
what am i doing wrong?

when i used:

```
after(function (done) {
    mongoose.unmock(function() {
        done();
    });
});
```

i get this error:

```
TypeError: Cannot set property '0' of undefined
    at node_modules/mockgoose/Mockgoose.js:190:29
    at node_modules/mongoose/lib/index.js:324:11
    at new Promise.ES6 (node_modules/mongoose/lib/promise.js:45:3)
    at Mongoose.disconnect (node_modules/mongoose/lib/index.js:323:37)
    at Mongoose.mongoose.unmock (node_modules/mockgoose/Mockgoose.js:188:18)
    at Context.<anonymous> (test.js:139:11)
```

**Comment by winfinit** [comment]
is this still a problem with most reset release? if so, please provide a complete test that i can copy and paste (es5) to debug this further.

**Comment by winfinit** [comment]
is this still an issue?

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
