### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'spawnSync'

### ISSUE THREAD

**Issue by scwood** [mccormicka/Mockgoose#205]
When running my Mocha tests:
```
  1)  "before each" hook:
     Uncaught TypeError: Object #<Object> has no method 'spawnSync'
      at start (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:70:26)
      at Object.start_server (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:65:16)
      at node_modules/mockgoose/Mockgoose.js:144:42
      at next (node_modules/mockgoose/node_modules/rimraf/rimraf.js:74:7)
      at CB (node_modules/mockgoose/node_modules/rimraf/rimraf.js:110:9)
      at node_modules/mockgoose/node_modules/rimraf/rimraf.js:136:14
      at Object.oncomplete (fs.js:108:15)
```

Here is my beforeEach hook:

```javascript
beforeEach(function (done) {
  mockgoose(mongoose).then(function () {
    var options = {
      replset: { rs_name: config.mongo.replicaSet },
      user: config.mongo.username,
      pass: config.mongo.password,
      auth: { authdb: config.mongo.authenticationDatabase },
    };
    mongoose.connect(config.mogno.testDatabasebUri, options);
    done();
  });
});
```

**Comment by winfinit** [comment]
working on it now, should be in a about 10-15 minutes

**Comment by winfinit** [comment]
@scwood thank you for reporting this issue, please try 6.0.2, that should work now.

**Comment by scwood** [comment]
Thanks for the help. Looks like it's working.
