### ISSUE TITLE
EventEmitter leak on mongoose disconnection

### ISSUE THREAD

**Issue by pibi** [mccormicka/Mockgoose#211]
Related to #178

PR #210 Solves this error:
```
.(node) warning: possible EventEmitter memory leak detected. 11 disconnected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at NativeConnection.addListener (events.js:239:17)
    at /home/prj/node_modules/mockgoose/Mockgoose.js:95:29
    at /home/prj/node_modules/mockgoose/Mockgoose.js:148:21
    at next (/home/prj/node_modules/mockgoose/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/home/prj/node_modules/mockgoose/node_modules/rimraf/rimraf.js:110:9)
```

while used with jasmine : 
```
  beforeEach(function(done) {
    require('../models/customers')();
    mockgoose(mongoose).then(function() {
      mongoose.connect('mongodb://example.com/TestingDB', function(err) {
        done(err);
      });
    });
  });

  afterEach(function(done) {
    mockgoose.reset(function() {
      mongoose.unmock(function() {
        mongoose.disconnect();
        delete mongoose.models.Customer;
        done();
      });
    });
  });
```

**Comment by pibi** [comment]
6b23162 merged the PR

**Comment by winfinit** [comment]
thank you @pibi
