### ISSUE TITLE
Mockgoose.reset throws error with createConnection

### ISSUE THREAD

**Issue by xscheiner** [mccormicka/Mockgoose#227]
I get this error in my code, but a simple test on the console can reproduce.

First test:

```
let mongoose = require("mongoose");
let mockgoose = require("mockgoose");
mockgoose(mongoose);
let a = mongoose.connect("xxx");
mockgoose.reset();  //works fine
```

Second test:

```
let mongoose = require("mongoose");
let mockgoose = require("mockgoose");
mockgoose(mongoose);
let a = mongoose.createConnection("xxx");
mockgoose.reset();  //error (below)

TypeError: Cannot read property 'dropDatabase' of undefined
    at Function.module.exports.reset (/dev/webapp-api-accounts/node_modules/mockgoose/Mockgoose.js:159:31)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1251:14)
    at next (native)
```

This is using mockgoose 6.0.8

**Comment by leopoldw** [comment]
Same for me

**Comment by winfinit** [comment]
you are not waiting for mockgoose to start, you need to use promises.

example from doc: 
```
var mongoose = require('mongoose');
var mockgoose = require('mockgoose');

mockgoose(mongoose).then(function() {
	// mongoose connection		
});
```

**Comment by winfinit** [comment]
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release
