### ISSUE TITLE
Errors when running tests

### ISSUE THREAD

**Issue by mansona** [mccormicka/Mockgoose#30]
Sorry for bugging you at this stage but i'm getting some errors when I run npm test. They are nothing to do with my PR https://github.com/mccormicka/Mockgoose/pull/27 , even though travis did seem to have a few issues (and not report a fail) https://travis-ci.org/mccormicka/Mockgoose/jobs/20453061

Here is the output of the npm test: (failures only)

```
Failures:

  1) Connection Tests Connect Connection should always be the same instance
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:99:29)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)

  2) Connection Tests Connect Be able to connect with just a host and database and port and options and callback
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:104:22)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at null._onTimeout (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2228:18)

  3) Connection Tests Connect Should NOT return an error when connecting to Mockgoose through connect
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:112:22)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)

  4) Connection Tests Connect Be able to connect with just a host
   Message:
     Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
   Stacktrace:
     Error: Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
    at new jasmine.ExpectationResult (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toThrow (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1369:29)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:123:20)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)
    at jasmine.WaitsForBlock.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2764:5)
    at null._onTimeout (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2778:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  5) Connection Tests Connect Be able to connect with just a host
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

  6) Connection Tests Connect Be able to connect with just a host and callback
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:127:22)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)

  7) Connection Tests Connect Be able to connect with just a host and database
   Message:
     Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
   Stacktrace:
     Error: Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
    at new jasmine.ExpectationResult (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toThrow (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1369:29)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:138:20)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)
    at jasmine.WaitsForBlock.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2764:5)
    at null._onTimeout (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2778:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  8) Connection Tests Connect Be able to connect with just a host and database
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

  9) Connection Tests Connect Be able to connect with just a host and database and callback
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:142:22)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)

  10) Connection Tests Connect Be able to connect with just a host and database and port
   Message:
     Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
   Stacktrace:
     Error: Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
    at new jasmine.ExpectationResult (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toThrow (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1369:29)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:153:20)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)
    at jasmine.WaitsForBlock.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2764:5)
    at null._onTimeout (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2778:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  11) Connection Tests Connect Be able to connect with just a host and database and port
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

  12) Connection Tests Connect Be able to connect with just a host and database and port and callback
   Message:
     TypeError: Cannot read property 'connection' of undefined
   Stacktrace:
     TypeError: Cannot read property 'connection' of undefined
    at /apps/Mockgoose/Mockgoose.js:111:50
    at NativeConnection.Connection.error (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:388:24)
    at NativeConnection.Connection.open (/apps/Mockgoose/node_modules/mongoose/lib/connection.js:212:10)
    at Mongoose.connect [as originalConnect] (/apps/Mockgoose/node_modules/mongoose/lib/index.js:211:15)
    at Mongoose.mongoose.connect (/apps/Mockgoose/Mockgoose.js:110:51)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:157:22)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)

  13) Connection Tests Connect Be able to connect with just a host and database and port and options
   Message:
     Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
   Stacktrace:
     Error: Expected function not to throw an exception , but it threw Cannot read property 'connection' of undefined
    at new jasmine.ExpectationResult (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toThrow (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1369:29)
    at null.<anonymous> (/apps/Mockgoose/test/Connectin.spec.js:168:20)
    at null.<anonymous> (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)
    at jasmine.Block.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1198:17)
    at jasmine.Queue.next_ (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2238:31)
    at onComplete (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2234:18)
    at jasmine.WaitsForBlock.execute (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2764:5)
    at null._onTimeout (/apps/Mockgoose/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2778:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  14) Connection Tests Connect Be able to connect with just a host and database and port and options
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 38.787 seconds
154 tests, 1008 assertions, 14 failures
0 skipped assertions
```

**Comment by sumitpramanik** [comment]
Hi , while trying to run test.js as node application, i am getting the following error.

D:\Repos\Mockgoose-master\node_modules\mongodb-prebuilt\index.js:155
    var bin_path = bin_path(version);
                   ^

TypeError: bin_path is not a function
    at install (D:\Repos\Mockgoose-master\node_modules\mongodb-prebuilt\index.js:155:20)
    at Object.start_server (D:\Repos\Mockgoose-master\node_modules\mongodb-prebuilt\index.js:57:16)
    at D:\Repos\Mockgoose-master\Mockgoose.js:144:42
    at next (D:\Repos\Mockgoose-master\node_modules\rimraf\rimraf.js:74:7)
    at CB (D:\Repos\Mockgoose-master\node_modules\rimraf\rimraf.js:110:9)
    at FSReqWrap.oncomplete (D:\Repos\Mockgoose-master\node_modules\rimraf\rimraf.js:225:7)


Has anyone got this error .. Plssss help

**Comment by bhushanvadgave** [comment]
Hello @sumitpramanik , I got the same error "TypeError: bin_path is not a function" on my windows system. I am using Mockgoose 6.0.3 and Mongoose 4.5.1. Have you fixed it?

**Comment by BenBestmann** [comment]
Reinstalling mockgoose using `npm install --save-dev mockgoose` fixed the problem for me. I think it has something to do with the prebuilt mongodb installation, but I am not sure.
