### ISSUE TITLE
Mockgoose needs stream support

### ISSUE THREAD

**Issue by nukulb** [mccormicka/Mockgoose#44]
```
var stream = Model.find().stream();

stream.on('data', function (doc) {
  if (somethingHappened) {
    this.pause()

    var self = this
    return bakeSomePizza(function () {
      self.resume()
    })
  }

  res.write(doc)
})

stream.on('error', function (err) {
  // handle err
})

stream.on('close', function () {
  // all done
})
```

right now following error is thrown
```
TypeError: Object #<Object> has no method 'nextObject'
    at QueryStream.__next (/Users/nukulb/src/hubba-node/node_modules/mongoose/lib/querystream.js:162:16)
    at QueryStream._next (/Users/nukulb/src/hubba-node/node_modules/mongoose/lib/querystream.js:145:15)
    at /Users/nukulb/src/hubba-node/node_modules/mongoose/lib/querystream.js:118:10
    at Collection.find (/Users/nukulb/src/hubba-node/node_modules/mockgoose/lib/Collection.js:102:13)
    at QueryStream._init (/Users/nukulb/src/hubba-node/node_modules/mongoose/lib/querystream.js:115:20)
    at /Users/nukulb/src/hubba-node/node_modules/mongoose/lib/querystream.js:59:10
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by alexraj** [comment]
I fixed this by modifying the find method in Collections.js as follows.
```
    this.find = function (conditions, options, callback) {
        if (! conn._mockReadyState) {
            return callback(new utils.ConnectionError());
        }
        var results;
        var models = db[name];
        if (!_.isEmpty(conditions)) {
            results = utils.findModelQuery(models, conditions);
        } else {
            results = utils.objectToArray(utils.cloneItems(models));
        }
        results = filter.applyOptions(options, results);

        if (results.name === 'MongoError') {
            callback(results);
        } else {
            var result = {
                toArray: function (callback) {
                    callback(null, results);
                }
            };
            result.results = results;
            result.size = results.length;
            result.current = -1;
            result.nextObject = function(cb) {
                result.current = result.current + 1;
                cb(null, result.current<result.size?result.results[result.current]:null);
            };
            result.close = function() {
            };
            callback(null, result);
        }
    };
```

**Comment by winfinit** [comment]
this should be supported in 5.0
