### ISSUE TITLE
Cannot find module 'node-uuid'

### ISSUE THREAD

**Issue by mattdeluco** [mccormicka/Mockgoose#71]
I get the following error when running my node/express server.  Why is code being loaded from mockgoose's test directory?

What's really odd is that I get this error even when I remove references to mockgoose from my project (but leave the module in the node_modules directory.)

```
/usr/local/bin/node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/matt/project/node_modules/mockgoose/test/models/ChildModel.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Process finished with exit code 8
```

**Comment by dokuboyejo** [comment]
Hi matdeluco,

Please could you specify in particular the procedure you used in solving the problem
